name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # 或者你希望触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # 如果你有子模块
          fetch-depth: 0  # 获取整个历史记录，以便版本控制工作

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20 # 或者你想要的 Node.js 版本
      
      - name: Install specific version of npm
        run: npm install -g npm@10.8.2 # 或者你想要的npm版本

      - name: Build Docs
        run: |
          npm ci
          npm run docs:build
      
      - name: Check .vuepress/dist Directory
        run: ls -la .vuepress/dist # 这一步是为了确认目录中是否有文件
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./.vuepress/dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: gh-pages # 明确指定部署到 gh-pages 分支
          force_orphan: true # 如果你希望删除 gh-pages 分支上的所有其他文件